"""app_settings 테이블 (T-014)

Revision ID: 3ecd068bcbc7
Revises: 7af56d820157
Create Date: 2026-08-04 21:45:26.611042

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3ecd068bcbc7"
down_revision: str | None = "7af56d820157"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###
    # Supabase가 public 스키마를 PostgREST로 노출하므로
    # RLS 없이는 Security Advisor 에러 + PII 노출 위험 (C2, T-002b).
    op.execute("ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_settings")
    # ### end Alembic commands ###
