"""core schema: member_programs, newsletters, send_logs, engagement_events

Revision ID: 59dda42e7213
Revises: 5d720a0e57b9
Create Date: 2026-07-12 16:15:38.837926

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "59dda42e7213"
down_revision: str | None = "5d720a0e57b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("html_body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text_body", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_filter", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("total_recipients", sa.Integer(), nullable=False),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_newsletters_status"), "newsletters", ["status"], unique=False)
    op.create_table(
        "member_programs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("program", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cohort", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "program", name="uq_member_programs_member_program"),
    )
    op.create_index(
        op.f("ix_member_programs_member_id"), "member_programs", ["member_id"], unique=False
    )
    op.create_index(
        op.f("ix_member_programs_program"), "member_programs", ["program"], unique=False
    )
    op.create_table(
        "send_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("newsletter_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["newsletter_id"],
            ["newsletters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id"),
    )
    op.create_index(op.f("ix_send_logs_email"), "send_logs", ["email"], unique=False)
    op.create_index(op.f("ix_send_logs_member_id"), "send_logs", ["member_id"], unique=False)
    op.create_index(
        op.f("ix_send_logs_newsletter_id"), "send_logs", ["newsletter_id"], unique=False
    )
    op.create_index(op.f("ix_send_logs_status"), "send_logs", ["status"], unique=False)
    op.create_table(
        "engagement_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("send_log_id", sa.Integer(), nullable=True),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("newsletter_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("provider_event_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["newsletter_id"],
            ["newsletters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["send_log_id"],
            ["send_logs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_event_id"),
    )
    op.create_index(
        op.f("ix_engagement_events_event_type"), "engagement_events", ["event_type"], unique=False
    )
    op.create_index(
        "ix_engagement_events_member_occurred",
        "engagement_events",
        ["member_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_engagement_events_newsletter_type",
        "engagement_events",
        ["newsletter_id", "event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_engagement_events_send_log_id"), "engagement_events", ["send_log_id"], unique=False
    )
    op.add_column("members", sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column(
        "members", sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "members", sa.Column("subcategory", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "members", sa.Column("position", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "members", sa.Column("organization", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "members", sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "members", sa.Column("division", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "members", sa.Column("business_area", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "members", sa.Column("membership_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "members", sa.Column("membership_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "members", sa.Column("payment_history", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "members", sa.Column("benefit_pct", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "members", sa.Column("council_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column("members", sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column(
        "members", sa.Column("unsubscribe_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # 기존 행 존재 시 NOT NULL 추가가 실패하지 않도록 server_default 부여
    op.add_column(
        "members",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "members",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_members_program"), table_name="members")
    op.create_index(op.f("ix_members_category"), "members", ["category"], unique=False)
    op.create_index(
        op.f("ix_members_membership_status"), "members", ["membership_status"], unique=False
    )
    op.create_unique_constraint("uq_members_unsubscribe_token", "members", ["unsubscribe_token"])
    # 기존 program 값을 member_programs로 이관한 뒤 컬럼 제거 (데이터 보존)
    op.execute(
        "INSERT INTO member_programs (member_id, program, created_at) "
        "SELECT id, program, now() FROM members WHERE program IS NOT NULL"
    )
    op.drop_column("members", "program")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("members", sa.Column("program", sa.VARCHAR(), autoincrement=False, nullable=True))
    # member_programs에서 program 값 복원 (회원당 첫 프로그램)
    op.execute(
        "UPDATE members SET program = ("
        "SELECT mp.program FROM member_programs mp "
        "WHERE mp.member_id = members.id ORDER BY mp.id LIMIT 1)"
    )
    op.drop_constraint("uq_members_unsubscribe_token", "members", type_="unique")
    op.drop_index(op.f("ix_members_membership_status"), table_name="members")
    op.drop_index(op.f("ix_members_category"), table_name="members")
    op.create_index(op.f("ix_members_program"), "members", ["program"], unique=False)
    op.alter_column(
        "members",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("members", "updated_at")
    op.drop_column("members", "unsubscribe_token")
    op.drop_column("members", "notes")
    op.drop_column("members", "council_label")
    op.drop_column("members", "benefit_pct")
    op.drop_column("members", "payment_history")
    op.drop_column("members", "membership_type")
    op.drop_column("members", "membership_status")
    op.drop_column("members", "business_area")
    op.drop_column("members", "division")
    op.drop_column("members", "location")
    op.drop_column("members", "organization")
    op.drop_column("members", "position")
    op.drop_column("members", "subcategory")
    op.drop_column("members", "category")
    op.drop_column("members", "phone")
    op.drop_index(op.f("ix_engagement_events_send_log_id"), table_name="engagement_events")
    op.drop_index("ix_engagement_events_newsletter_type", table_name="engagement_events")
    op.drop_index("ix_engagement_events_member_occurred", table_name="engagement_events")
    op.drop_index(op.f("ix_engagement_events_event_type"), table_name="engagement_events")
    op.drop_table("engagement_events")
    op.drop_index(op.f("ix_send_logs_status"), table_name="send_logs")
    op.drop_index(op.f("ix_send_logs_newsletter_id"), table_name="send_logs")
    op.drop_index(op.f("ix_send_logs_member_id"), table_name="send_logs")
    op.drop_index(op.f("ix_send_logs_email"), table_name="send_logs")
    op.drop_table("send_logs")
    op.drop_index(op.f("ix_member_programs_program"), table_name="member_programs")
    op.drop_index(op.f("ix_member_programs_member_id"), table_name="member_programs")
    op.drop_table("member_programs")
    op.drop_index(op.f("ix_newsletters_status"), table_name="newsletters")
    op.drop_table("newsletters")
    # ### end Alembic commands ###
