"""members table

Revision ID: 5d720a0e57b9
Revises:
Create Date: 2026-07-12 15:34:05.276291

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "5d720a0e57b9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "members",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("program", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subscribed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_members_email"), "members", ["email"], unique=False)
    op.create_index(op.f("ix_members_name"), "members", ["name"], unique=False)
    op.create_index(op.f("ix_members_program"), "members", ["program"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_members_program"), table_name="members")
    op.drop_index(op.f("ix_members_name"), table_name="members")
    op.drop_index(op.f("ix_members_email"), table_name="members")
    op.drop_table("members")
    # ### end Alembic commands ###
