"""news_items 테이블 (T-006 분류 저장)

Revision ID: 61c5f308e719
Revises: 099fd24371d6
Create Date: 2026-07-18 20:18:31.072084

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "61c5f308e719"
down_revision: str | None = "099fd24371d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("origin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_items_category"), "news_items", ["category"], unique=False)
    op.create_index(op.f("ix_news_items_url"), "news_items", ["url"], unique=True)
    # Supabase PostgREST 노출 방어 — 새 테이블은 RLS 필수 (C2 규칙, T-002b 참고)
    op.execute("ALTER TABLE news_items ENABLE ROW LEVEL SECURITY")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_news_items_url"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_category"), table_name="news_items")
    op.drop_table("news_items")
    # ### end Alembic commands ###
