"""pilot_members table

Revision ID: 7af56d820157
Revises: 61c5f308e719
Create Date: 2026-07-28 00:45:31.199166

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7af56d820157"
down_revision: str | None = "61c5f308e719"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pilot_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("position", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("program", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("org_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("organization", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("group_no", sa.Integer(), nullable=True),
        sa.Column("subscribed", sa.Boolean(), nullable=False),
        sa.Column("unsubscribe_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("emails_sent", sa.Integer(), nullable=False),
        sa.Column("emails_opened", sa.Integer(), nullable=False),
        sa.Column("links_clicked", sa.Integer(), nullable=False),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_clicked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "category_clicks",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "category_opens",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("activity_score", sa.Float(), nullable=False),
        sa.Column("activity_tier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("score_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pilot_members_activity_tier"), "pilot_members", ["activity_tier"], unique=False
    )
    op.create_index(op.f("ix_pilot_members_email"), "pilot_members", ["email"], unique=False)
    op.create_index(op.f("ix_pilot_members_group_no"), "pilot_members", ["group_no"], unique=False)
    op.create_index(op.f("ix_pilot_members_member_id"), "pilot_members", ["member_id"], unique=True)
    op.create_index(op.f("ix_pilot_members_org_type"), "pilot_members", ["org_type"], unique=False)
    op.create_index(op.f("ix_pilot_members_program"), "pilot_members", ["program"], unique=False)
    # ### end Alembic commands ###
    # C2: Supabase가 public 스키마를 PostgREST로 노출 → RLS 없으면 Security Advisor 에러 + PII 노출.
    op.execute("ALTER TABLE pilot_members ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pilot_members_program"), table_name="pilot_members")
    op.drop_index(op.f("ix_pilot_members_org_type"), table_name="pilot_members")
    op.drop_index(op.f("ix_pilot_members_member_id"), table_name="pilot_members")
    op.drop_index(op.f("ix_pilot_members_group_no"), table_name="pilot_members")
    op.drop_index(op.f("ix_pilot_members_email"), table_name="pilot_members")
    op.drop_index(op.f("ix_pilot_members_activity_tier"), table_name="pilot_members")
    op.drop_table("pilot_members")
    # ### end Alembic commands ###
